version: '3.8'

services:
  technologian-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technologian-nextjs
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - technologian-network

networks:
  technologian-network:
    driver: bridge
